apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: $RTF_APP_NAME
  namespace: $RTF_DEFAULT_NS
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $RTF_APP_NAME
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75